export class Tickets {
  constructor(
    UserID: number,
    Username: string,
    TripID: number,
    BoaringGovernrateID: number,
    BoaringGovernratename: string,
    BoardingCityID: number,
    BoardingCityname: string,
    BoardingstationID: number,
    Boardingstationname: string,
    DestinationGovernrateID: number,
    DestinationGovernratename: string,
    DestinationCityID: number,
    DestinationCityname: string,
    DestinationstationID: number,
    DestinationstationName: string,
    OrganizationID: number,
    Organizationname: string,
    VehicleID: number,
    VehicleName: string,
    VehicleClass: string,
    BookingID: number,
    PNR: number,
    SeatNumber: number,
    SeatPrice: number,
    PassengerName: string,
    PassengerMobileNumber: number,
    PassengerNationalID: number,
    VehicleType: string,
    TripNotes: string
  ) {}
}
